#!/usr/bin/env bash
# EMMA Metropolis skill registry for the n8n workflow bundle.
# Source this file before local maintenance scripts if you need a single list of
# workflow skills and the workflow names used by the master orchestrator.

export EMMA_DEFAULT_MODEL="models/gemini-2.5-flash"

EMMA_SKILLS=(
  "LEAD=LEAD_ENGINE_V700"
  "SALES=SALES_ENGINE_V700"
  "SUPERNOVA=SUPERNOVA_ENGINE_V_INFINITY"
  "CONTENT=CONTENT_ENGINE_V700"
  "CRM=CRM_ENGINE_V700"
  "KI_AGENT=KI_AGENT_ENGINE_V700"
  "LEGAL=LEGAL_ENGINE_V14"
  "FINANCE=FINANCE_ENGINE_V14"
  "VENTURE=VENTURE_ENGINE_V14"
  "INTEL=INTEL_ENGINE_V14"
  "GITHUB=GITHUB_ENGINE_V700"
  "ASANA=ASANA_ENGINE_V700"
  "SHOPIFY=SHOPIFY_ENGINE_V700"
  "WORDPRESS=WORDPRESS_ENGINE_V700"
  "DISCORD=DISCORD_ENGINE_V700"
  "GOOGLE_SUITE=GOOGLE_SUITE_ENGINE_V700"
  "EMAIL_VALIDATION=EMAIL_VALIDATION_ENGINE_V700"
  "GUARDIAN=GUARDIAN_ENGINE_V700"
  "PRICING=PRICING_ENGINE_V700"
  "QUICKCHART=QUICKCHART_ENGINE_V700"
  "REACTIVATION=REACTIVATION_ENGINE_V700"
  "SPOTIFY=SPOTIFY_ENGINE_V700"
  "STREAMS=STREAMS_ENGINE_V700"
  "EVOLUTION=EVOLUTION_ENGINE_V700"
  "INTELLIGENCE=INTELLIGENCE_ENGINE_V700"
  "BITWARDEN=BITWARDEN_ENGINE_V700"
  "DRIVE=DRIVE_ENGINE_V700"
  "LOGGING=LOGGING_ENGINE_V700"
  "KPI=METROPOLIS_KPI_REGISTRY"
  "MULTI_AGENT=METROPOLIS_MULTI_AGENT_CORE"
  "SYNC=METROPOLIS_V14_SYNC_BRIDGE"
  "VECTOR_MEMORY=VECTOR_MEMORY_ENGINE_V700"
  "SELF_BUILDER=EMMA_SELF_BUILDER"
)

emma_workflow_for_skill() {
  local requested="$1"
  local entry
  for entry in "${EMMA_SKILLS[@]}"; do
    if [[ "${entry%%=*}" == "$requested" ]]; then
      printf '%s\n' "${entry#*=}"
      return 0
    fi
  done
  return 1
}

emma_print_skills() {
  printf '%s\n' "${EMMA_SKILLS[@]}"
}
